export const FETCH_POSTS = 'FETCH_POSTS'

export const FETCH_ADD_POST = 'FETCH_ADD_POST'

export const FETCH_EDIT_POST = 'FETCH_EDIT_POST'

export const FETCH_POST_DELETE = 'FETCH_POST_DELETE'

export const FETCH_ADD_COMMENT = 'ADD_COMMENT'

export const FETCH_POST = 'FETCH_POST'

export const ADD_SINGLE_LOADED_POST = 'ADD_SINGLE_LOADED_POST'

export const SET_EDITABLE_POST = 'SET_EDITABLE_POST'

export const FETCH_EDIT_COMMENT = 'EDIT_COMMENT'

export const FETCH_COMMENT_DELETE = 'FETCH_COMMENT_DELETE'

export const SET_EDITABLE = 'SET_EDITABLE'


export const _SUCCESS = '_SUCCESS'

export const _FAILURE = '_FAILURE'

export const _REQUEST = '_REQUEST'


export const CHANGE_SELECTION = 'CHANGE_SELECTION'

export const CHANGE_DAY_RANGE = 'CHANGE_DAY_RANGE'

export const FETCH_COMMENTS = 'FETCH_COMMENTS'


export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'

export const FETCH_ADD_CATEGORY = 'FETCH_ADD_CATEGORY'

export const FETCH_CATEGORY_DELETE = 'FETCH_CATEGORY_DELETE'

export const CATEGORY_SELECT = 'CATEGORY_SELECT'

export const FETCH_CATEGORIZED_POSTS = 'FETCH_CATEGORIZED_POSTS'

export const ADD_LOADED_CATEGORY = 'ADD_LOADED_CATEGORY'