
export const FETCH_POSTS = 'FETCH_POSTS'

export const _SUCCESS = '_SUCCESS'

export const _FAILURE = '_FAILURE'

export const _REQUEST = '_REQUEST'

export const FETCH_ADD_POST = 'FETCH_ADD_POST'

export const FETCH_POST_DELETE = 'FETCH_POST_DELETE'

export const CHANGE_SELECTION = 'CHANGE_SELECTION'

export const ADD_COMMENT = 'ADD_COMMENT'

export const EDIT_COMMENT = 'EDIT_COMMENT'

export const FETCH_COMMENT_DELETE = 'FETCH_COMMENT_DELETE'

export const SET_EDITABLE = 'SET_EDITABLE'

export const CHANGE_DAY_RANGE = 'CHANGE_DAY_RANGE'

export const FETCH_COMMENTS = 'FETCH_COMMENTS'